[package]
name = "npm-registry-client"
description = "npm registry API wrapper"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/rust-npm-registry-client"
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
